// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: strangelove_ventures/poa/v1/query.proto

package poa

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryPendingValidatorsRequest is the request type for the Query/PendingValidators RPC method.
type QueryPendingValidatorsRequest struct {
}

func (m *QueryPendingValidatorsRequest) Reset()         { *m = QueryPendingValidatorsRequest{} }
func (m *QueryPendingValidatorsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPendingValidatorsRequest) ProtoMessage()    {}
func (*QueryPendingValidatorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_676fcce3868e4c52, []int{0}
}
func (m *QueryPendingValidatorsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPendingValidatorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPendingValidatorsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPendingValidatorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPendingValidatorsRequest.Merge(m, src)
}
func (m *QueryPendingValidatorsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPendingValidatorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPendingValidatorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPendingValidatorsRequest proto.InternalMessageInfo

// QueryPendingValidatorResponse is the response type for the Query/PendingValidators RPC method.
type PendingValidatorsResponse struct {
	// Pending is the returned pending validators from the module
	Pending []Validator `protobuf:"bytes,1,rep,name=pending,proto3" json:"pending"`
}

func (m *PendingValidatorsResponse) Reset()         { *m = PendingValidatorsResponse{} }
func (m *PendingValidatorsResponse) String() string { return proto.CompactTextString(m) }
func (*PendingValidatorsResponse) ProtoMessage()    {}
func (*PendingValidatorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_676fcce3868e4c52, []int{1}
}
func (m *PendingValidatorsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PendingValidatorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PendingValidatorsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PendingValidatorsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingValidatorsResponse.Merge(m, src)
}
func (m *PendingValidatorsResponse) XXX_Size() int {
	return m.Size()
}
func (m *PendingValidatorsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingValidatorsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PendingValidatorsResponse proto.InternalMessageInfo

func (m *PendingValidatorsResponse) GetPending() []Validator {
	if m != nil {
		return m.Pending
	}
	return nil
}

// QueryConsensusPowerRequest is the request type for the Query/ConsensusPower RPC method.
type QueryConsensusPowerRequest struct {
	// validator_address is the address of the validator
	ValidatorAddress string `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
}

func (m *QueryConsensusPowerRequest) Reset()         { *m = QueryConsensusPowerRequest{} }
func (m *QueryConsensusPowerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryConsensusPowerRequest) ProtoMessage()    {}
func (*QueryConsensusPowerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_676fcce3868e4c52, []int{2}
}
func (m *QueryConsensusPowerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryConsensusPowerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryConsensusPowerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryConsensusPowerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryConsensusPowerRequest.Merge(m, src)
}
func (m *QueryConsensusPowerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryConsensusPowerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryConsensusPowerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryConsensusPowerRequest proto.InternalMessageInfo

func (m *QueryConsensusPowerRequest) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

// QueryConsensusPowerResponse is the response type for the Query/ConsensusPowerRequest RPC method.
type QueryConsensusPowerResponse struct {
	// consensus_power is the returned consensus power from the BFT consensus mechanism
	ConsensusPower int64 `protobuf:"varint,1,opt,name=consensus_power,json=consensusPower,proto3" json:"consensus_power,omitempty"`
}

func (m *QueryConsensusPowerResponse) Reset()         { *m = QueryConsensusPowerResponse{} }
func (m *QueryConsensusPowerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryConsensusPowerResponse) ProtoMessage()    {}
func (*QueryConsensusPowerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_676fcce3868e4c52, []int{3}
}
func (m *QueryConsensusPowerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryConsensusPowerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryConsensusPowerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryConsensusPowerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryConsensusPowerResponse.Merge(m, src)
}
func (m *QueryConsensusPowerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryConsensusPowerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryConsensusPowerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryConsensusPowerResponse proto.InternalMessageInfo

func (m *QueryConsensusPowerResponse) GetConsensusPower() int64 {
	if m != nil {
		return m.ConsensusPower
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryPendingValidatorsRequest)(nil), "strangelove_ventures.poa.v1.QueryPendingValidatorsRequest")
	proto.RegisterType((*PendingValidatorsResponse)(nil), "strangelove_ventures.poa.v1.PendingValidatorsResponse")
	proto.RegisterType((*QueryConsensusPowerRequest)(nil), "strangelove_ventures.poa.v1.QueryConsensusPowerRequest")
	proto.RegisterType((*QueryConsensusPowerResponse)(nil), "strangelove_ventures.poa.v1.QueryConsensusPowerResponse")
}

func init() {
	proto.RegisterFile("strangelove_ventures/poa/v1/query.proto", fileDescriptor_676fcce3868e4c52)
}

var fileDescriptor_676fcce3868e4c52 = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x4f, 0xeb, 0xd3, 0x30,
	0x1c, 0xc6, 0x9b, 0xcd, 0x3f, 0x18, 0x61, 0xba, 0x20, 0xb8, 0x75, 0xb3, 0x1b, 0x15, 0xdc, 0x60,
	0xd8, 0xb2, 0x09, 0x2a, 0x82, 0x07, 0x27, 0x0c, 0xbc, 0xcd, 0x1e, 0x3c, 0x78, 0x29, 0x59, 0x1b,
	0x6a, 0x61, 0x4b, 0xb2, 0x24, 0xad, 0x78, 0xf5, 0x15, 0x08, 0xbe, 0x05, 0x6f, 0xbe, 0x91, 0x1d,
	0x07, 0x5e, 0x3c, 0x88, 0xc8, 0xe6, 0x0b, 0x91, 0xfe, 0x75, 0xd3, 0x5a, 0xf9, 0xdd, 0x4a, 0x9f,
	0xe7, 0xfb, 0xe4, 0xf3, 0x7d, 0x12, 0x38, 0x92, 0x4a, 0x60, 0x1a, 0x90, 0x35, 0x8b, 0x89, 0x1b,
	0x13, 0xaa, 0x22, 0x41, 0xa4, 0xcd, 0x19, 0xb6, 0xe3, 0xa9, 0xbd, 0x8d, 0x88, 0x78, 0x67, 0x71,
	0xc1, 0x14, 0x43, 0xbd, 0x2a, 0xa3, 0xc5, 0x19, 0xb6, 0xe2, 0xa9, 0x7e, 0x2b, 0x60, 0x01, 0x4b,
	0x7d, 0x76, 0xf2, 0x95, 0x8d, 0xe8, 0xfd, 0x80, 0xb1, 0x60, 0x4d, 0x6c, 0xcc, 0x43, 0x1b, 0x53,
	0xca, 0x14, 0x56, 0x21, 0xa3, 0x32, 0x57, 0xc7, 0x75, 0x27, 0x73, 0x2c, 0xf0, 0xa6, 0x70, 0x4e,
	0xea, 0x9c, 0x31, 0x5e, 0x87, 0x3e, 0x56, 0x4c, 0x64, 0x66, 0x73, 0x00, 0xef, 0xbc, 0x4c, 0xb0,
	0x97, 0x84, 0xfa, 0x21, 0x0d, 0x5e, 0x15, 0xb2, 0x74, 0xc8, 0x36, 0x22, 0x52, 0x99, 0x1e, 0xec,
	0x56, 0x68, 0x92, 0x33, 0x2a, 0x09, 0x5a, 0xc0, 0xab, 0x3c, 0x13, 0x3b, 0x60, 0xd8, 0x1c, 0x5f,
	0x9f, 0xdd, 0xb3, 0x6a, 0xf6, 0xb6, 0xca, 0x84, 0xf9, 0xa5, 0xdd, 0xf7, 0x81, 0xe6, 0x14, 0xc3,
	0xe6, 0x0b, 0xa8, 0xa7, 0x14, 0xcf, 0x93, 0x54, 0x2a, 0x23, 0xb9, 0x64, 0x6f, 0x89, 0xc8, 0x11,
	0xd0, 0x04, 0xb6, 0x4b, 0x6c, 0x17, 0xfb, 0xbe, 0x20, 0x52, 0x76, 0xc0, 0x10, 0x8c, 0xaf, 0x39,
	0x37, 0x4b, 0xe1, 0x59, 0xf6, 0xdf, 0x5c, 0xc0, 0x5e, 0x65, 0x54, 0x4e, 0x3c, 0x82, 0x37, 0xbc,
	0x42, 0x71, 0x79, 0x22, 0xa5, 0x49, 0x4d, 0xa7, 0xe5, 0x9d, 0x0d, 0xcc, 0xbe, 0x35, 0xe0, 0xe5,
	0x34, 0x08, 0x7d, 0x06, 0xb0, 0xfd, 0x57, 0x05, 0xe8, 0x49, 0xed, 0xa6, 0xb5, 0x9d, 0xea, 0x0f,
	0x6b, 0x67, 0xff, 0x59, 0xb7, 0x69, 0xbe, 0xff, 0xf2, 0xf3, 0x63, 0xa3, 0x8f, 0xf4, 0xf2, 0xde,
	0x33, 0xab, 0x1b, 0xff, 0xe6, 0xfa, 0x04, 0x60, 0xeb, 0x7c, 0x77, 0xf4, 0xe8, 0xff, 0xa8, 0x95,
	0xc5, 0xeb, 0x8f, 0x2f, 0x3e, 0x98, 0x93, 0x0e, 0x52, 0xd2, 0x2e, 0xba, 0x5d, 0x90, 0xfe, 0x51,
	0xfa, 0xfc, 0xe9, 0xee, 0x60, 0x80, 0xfd, 0xc1, 0x00, 0x3f, 0x0e, 0x06, 0xf8, 0x70, 0x34, 0xb4,
	0xfd, 0xd1, 0xd0, 0xbe, 0x1e, 0x0d, 0xed, 0xf5, 0xdd, 0x20, 0x54, 0x6f, 0xa2, 0x95, 0xe5, 0xb1,
	0x8d, 0x7d, 0x72, 0xfc, 0xfd, 0xd3, 0x97, 0xbc, 0xba, 0x92, 0xbe, 0xde, 0x07, 0xbf, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x2c, 0xb8, 0x2b, 0x91, 0x90, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// PendingValidators returns currently pending validators of the module.
	PendingValidators(ctx context.Context, in *QueryPendingValidatorsRequest, opts ...grpc.CallOption) (*PendingValidatorsResponse, error)
	// ConsensusPower returns the current consensus power of a validator.
	ConsensusPower(ctx context.Context, in *QueryConsensusPowerRequest, opts ...grpc.CallOption) (*QueryConsensusPowerResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) PendingValidators(ctx context.Context, in *QueryPendingValidatorsRequest, opts ...grpc.CallOption) (*PendingValidatorsResponse, error) {
	out := new(PendingValidatorsResponse)
	err := c.cc.Invoke(ctx, "/strangelove_ventures.poa.v1.Query/PendingValidators", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ConsensusPower(ctx context.Context, in *QueryConsensusPowerRequest, opts ...grpc.CallOption) (*QueryConsensusPowerResponse, error) {
	out := new(QueryConsensusPowerResponse)
	err := c.cc.Invoke(ctx, "/strangelove_ventures.poa.v1.Query/ConsensusPower", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// PendingValidators returns currently pending validators of the module.
	PendingValidators(context.Context, *QueryPendingValidatorsRequest) (*PendingValidatorsResponse, error)
	// ConsensusPower returns the current consensus power of a validator.
	ConsensusPower(context.Context, *QueryConsensusPowerRequest) (*QueryConsensusPowerResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) PendingValidators(ctx context.Context, req *QueryPendingValidatorsRequest) (*PendingValidatorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PendingValidators not implemented")
}
func (*UnimplementedQueryServer) ConsensusPower(ctx context.Context, req *QueryConsensusPowerRequest) (*QueryConsensusPowerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConsensusPower not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_PendingValidators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPendingValidatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PendingValidators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/strangelove_ventures.poa.v1.Query/PendingValidators",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PendingValidators(ctx, req.(*QueryPendingValidatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ConsensusPower_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryConsensusPowerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ConsensusPower(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/strangelove_ventures.poa.v1.Query/ConsensusPower",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ConsensusPower(ctx, req.(*QueryConsensusPowerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "strangelove_ventures.poa.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PendingValidators",
			Handler:    _Query_PendingValidators_Handler,
		},
		{
			MethodName: "ConsensusPower",
			Handler:    _Query_ConsensusPower_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "strangelove_ventures/poa/v1/query.proto",
}

func (m *QueryPendingValidatorsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPendingValidatorsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPendingValidatorsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *PendingValidatorsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PendingValidatorsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PendingValidatorsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Pending) > 0 {
		for iNdEx := len(m.Pending) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Pending[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryConsensusPowerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryConsensusPowerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryConsensusPowerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryConsensusPowerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryConsensusPowerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryConsensusPowerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ConsensusPower != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ConsensusPower))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryPendingValidatorsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *PendingValidatorsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Pending) > 0 {
		for _, e := range m.Pending {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryConsensusPowerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryConsensusPowerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ConsensusPower != 0 {
		n += 1 + sovQuery(uint64(m.ConsensusPower))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryPendingValidatorsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPendingValidatorsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPendingValidatorsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PendingValidatorsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PendingValidatorsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PendingValidatorsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pending", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pending = append(m.Pending, Validator{})
			if err := m.Pending[len(m.Pending)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryConsensusPowerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryConsensusPowerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryConsensusPowerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryConsensusPowerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryConsensusPowerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryConsensusPowerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsensusPower", wireType)
			}
			m.ConsensusPower = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConsensusPower |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
