ictest-poa:
	go clean -testcache && go test -race -v -run TestPOABase .

ictest-jail:
	go clean -testcache && go test -race -v -run TestPOAJailing .

ictest-val-add:
	go clean -testcache && go test -race -v -run TestPOAAddValidator .