name: Simulator tests
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          check-latest: true
      - name: Full application simulation (fixed seed)
        run: make sim-full-app
      - name: Simulation after state import (fixed seed)
        run: make sim-after-import
      - name: Simulation import/export (fixed seed)
        run: make sim-import-export
      - name: Simulate application state determinism (fixed seed)
        run: make sim-app-determinism
